// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),

  ic_back: require('../Images/ic_back.png'),
  ic_avatar: require('../Images/ic_avatar.png'),
  ic_camera: require('../Images/ic_camera.png'),
  bg_avatar: require('../Images/bg_avatar.png'),
  logo_uit: require('../Images/logo_uit.png'),
  ic_home: require('../Images/ic_home.png'),
  ic_menu: require('../Images/ic_menu.png'),
  ic_seat: require('../Images/ic_seat.png'),
  chair_top: require('../Images/chair_top.png'),
  chair_bottom: require('../Images/chair_bottom.png'),
  table_big_green: require('../Images/table_big_green.png'),
  table_big_pink: require('../Images/table_big_pink.png'),
  table_small_green: require('../Images/table_small_green.png'),
  table_small_yellow: require('../Images/table_small_yellow.png'),
  ic_book: require('../Images/ic_book.png'),
  ic_clock: require('../Images/ic_clock.png'),
  ic_add: require('../Images/ic_add.png'),
  ic_cancel: require('../Images/ic_cancel.png'),
}

export default images
